# Generated by Django 4.0 on 2021-12-21 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(max_length=120, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Service Name')),
                ('service_type', models.CharField(max_length=120, verbose_name='Service Type')),
                ('address', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=15)),
                ('professional', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.user')),
            ],
        ),
    ]
