# Generated by Django 4.0 on 2021-12-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.user'),
        ),
    ]
