# Generated by Django 4.0 on 2021-12-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_provider_id_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
